### ISSUE TITLE
Forbidden (#403) obtained during email confirmation if user already logged in

### ISSUE THREAD

**Issue by ghost** [yii2tech/authlog#2]
This mistake appeared after authlog was installed 

![screenshot2016-03-12_03 25 41](https://cloud.githubusercontent.com/assets/16696651/13720189/7512fab0-e802-11e5-9b5b-71cf8e96a412.png)

**Comment by klimov-paul** [comment]
Since I have no idea, what actions do you perform for 'user email confirmation', I can not help you.
Closed unless more coherit problem description provided.

**Comment by rumatakira** [comment]
Email confirmation - if the user use the link with token in his email, but at this moment has opened (or closed) browser window were he is already logged in - this mistake obtained. Otherwise - he normally redirected to the login page without the mistake. Or... maybe... the mistake is inhibited. Commonly - I use standard login, standard email confirmation which is supplied with advanced Yii and your extension.

**Comment by ghost** [comment]
My apologies Pavel - it is not your mistake. I have changed access rules in SiteController  and forgot about this. Oops...
